@startuml
skinparam classAttributeIconSize 0

class Ship {
  - shipName: String
  - shipCreationDate: String
  + Ship(shipName: String, shipCreationDate: String)
  + getShipName(): String
  + setShipName(shipName: String): void
  + getShipCreationDate(): String
  + setShipCreationDate(shipCreationDate: String): void
  + print(): void
}

class CruiseShip {
  - maxPassengers: int
  + CruiseShip(shipName: String, shipCreationDate: String, maxPassengers: int)
  + getMaxPassengers(): int
  + setMaxPassengers(maxPassengers: int): void
  + print(): void
}

class CargoShip {
  - cargoCapacity: int
  + CargoShip(shipName: String, shipCreationDate: String, cargoCapacity: int)
  + getCargoCapacity(): int
  + setCargoCapacity(cargoCapacity: int): void
  + print(): void
}

CruiseShip --|> Ship
CargoShip --|> Ship

@enduml